In [1]:
import numpy as np
import pandas as pd

import ogb
from ogb.nodeproppred import NodePropPredDataset
from torch_geometric.data import DataLoader

# Download and process data at './dataset/ogbg_molhiv/'
dataset = NodePropPredDataset(name = "ogbn-arxiv")
split_idx = dataset.get_idx_split()
train_idx, valid_idx, test_idx = split_idx["train"], split_idx["valid"], split_idx["test"]
graph = dataset[0] # pyg graph object

In [2]:

D=graph[0]
print(D)

E=D['edge_index']
print(E[0])
print(E[1])

Class=graph[1]
Node_Class=Class[:,0]
print(Node_Class)
df1 = pd.DataFrame(Class,columns=["Class"])
df1.head()

feature_names = ["w_{}".format(ii) for ii in range(128)]
print(feature_names)
Node_Fec=list(D['node_feat'])
df2 = pd.DataFrame(Node_Fec,columns=feature_names)
df2.head()

Data=pd.concat([df1, df2],axis=1)

catagories=Data['Class'].to_numpy()
data_by_class = {cls: Data.loc[Data['Class'] == cls].drop(['Class'], axis=1) for cls in range(max(catagories) + 1)}
def Average(lst):
    # average function
    avg = np.average(lst)
    return(avg)
sel_basis = [[Average(list(df[f'w_{i}'].to_numpy()))
              for i in range(len(df.columns))]
             for df in data_by_class.values()]
feature_names = ["w_{}".format(ii) for ii in range(128)]
Fec=[]
n=169343


Node_Year=D['node_year']
#print(Node_Year)
#print(len(Node_Year))
Node_Year_list=list(Node_Year[:,0])
Class=graph[1]
Node_Class=list(Class[:,0])
#print(Class)
#print(np.unique(Class))
#print(Node_Class)
E=D['edge_index']
EdgeL=E[0]
EdgeR=E[1]

Node_Year_list.index(2019)
list_size = len(Node_Year_list)
NIndex_19_20 = []
# declare for loop
for itr in range(list_size):

    # check the condition
    if (Node_Year_list[itr] == 2019):
        NIndex_19_20.append(itr)
    if (Node_Year_list[itr] == 2020):
        NIndex_19_20.append(itr)
N_class_train=Node_Class
for d in NIndex_19_20:
    N_class_train[d]=40


{'edge_index': array([[104447,  15858, 107156, ...,  45118,  45118,  45118],
       [ 13091,  47283,  69161, ..., 162473, 162537,  72717]]), 'edge_feat': None, 'node_feat': array([[-0.057943, -0.05253 , -0.072603, ...,  0.173364, -0.172796,
        -0.140059],
       [-0.1245  , -0.070665, -0.325202, ...,  0.068524, -0.372111,
        -0.301036],
       [-0.080242, -0.023328, -0.183787, ...,  0.109919,  0.117589,
        -0.139883],
       ...,
       [-0.22053 , -0.036568, -0.402199, ...,  0.11336 , -0.161393,
        -0.145171],
       [-0.138236,  0.040885, -0.251811, ..., -0.08929 , -0.041253,
        -0.376132],
       [-0.029875,  0.268417, -0.161124, ...,  0.120807,  0.077647,
        -0.091018]], dtype=float32), 'node_year': array([[2013],
       [2015],
       [2014],
       ...,
       [2020],
       [2020],
       [2020]]), 'num_nodes': 169343}
[104447  15858 107156 ...  45118  45118  45118]
[ 13091  47283  69161 ... 162473 162537  72717]
[ 4  5 28 ... 10  4  1]
['w_0', 'w_1

In [3]:
import pandas as pd

data = pd.read_csv('Feature_nbd_tran_OGB_Arxiv.csv')

data.head(10)

Unnamed: 0  I_0  O_0  I_1  O_1  I_2  O_2  I_3  O_3  I_4  ...      C_31  \
0           0    0    0    0    1    0    0    0    0    0  ...  1.377229   
1           1    0    0    0    0    0    0    0    0    0  ...  1.287860   
2           2    0    0    0    0    0    0    0    0    0  ...  1.066779   
3           3    0    0    0    0    0    0    0    0    0  ...  1.212923   
4           4    0    0    0    0    0    0    0    0    0  ...  1.312554   
5           5    0    0    0    0    0    0    0    0    0  ...  1.078765   
6           6    0    0    0    0    0    0    0    0    0  ...  1.241842   
7           7    0    0    0    0    0    0    0    0    1  ...  1.199062   
8           8    0    0    0    0    0    0    0    0    0  ...  1.786019   
9           9    0    0    0    0    0    0    0    0    0  ...  1.262207   

       C_32      C_33      C_34      C_35      C_36      C_37      C_38  \
0  1.454818  1.507436  1.475130  1.321142  1.332594  1.402960  1.464580   
1  1.287285  1.232101  1.173206  1.212150  1.203949  1.218569  1.392768   
2  1.054476  1.090065  1.106729  1.018415  1.048563  1.055761  0.872858   
3  1.329790  1.380889  1.407620  1.317958  1.232171  1.227022  1.067227   
4  1.071757  1.061597  0.951873  1.278025  1.154286  1.212957  1.561437   
5  0.970090  1.012655  0.896012  0.998846  0.993356  1.029007  1.191400   
6  1.335402  1.582994  1.495853  1.341021  1.469382  1.239008  1.392586   
7  1.267383  1.210855  1.198600  1.190745  1.114602  1.144420  1.301582   
8  1.951015  2.015311  2.024879  1.892484  1.863353  1.859816  1.721218   
9  1.185521  1.250311  1.150641  1.267055  1.228752  1.230345  1.561975   

       C_39  Class  
0  1.529985      4  
1  1.229372      5  
2  1.053669     28  
3  1.403863      8  
4  1.054831     27  
5  0.891102     34  
6  1.587203      6  
7  1.228871      4  
8  2.049513      3  
9  1.293345     28  

[10 rows x 204 columns]

In [6]:
#Spatial only
k = 80
feature = ["I_0", "O_0"]
for i in range(1, k - 1, 2):
    feature.append("I_{}".format(int((i + 1) / 2)))
    feature.append("O_{}".format(int((i + 1) / 2)))
#for i in range(40):
#    feature.append("C_{}".format(i))

X = data[feature]  # Features
y = data['Class']  # Labels
X_train = X.iloc[list(train_idx)+list(valid_idx)]
X_test = X.iloc[test_idx]
y_train = y.iloc[list(train_idx)+list(valid_idx)]
y_test = y.iloc[test_idx]
from xgboost import XGBClassifier

bst = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1)
bst.fit(X_train, y_train)
y_pred = bst.predict(X_test)
# Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(y_test, y_pred) * 100, "%")

Accuracy: 70.34545192683579 %


In [7]:
#Domain only
#k = 80
#feature = ["I_0", "O_0"]
#for i in range(1, k - 1, 2):
#    feature.append("I_{}".format(int((i + 1) / 2)))
#    feature.append("O_{}".format(int((i + 1) / 2)))
for i in range(40):
    feature.append("C_{}".format(i))

X = data[feature]  # Features
y = data['Class']  # Labels
X_train = X.iloc[list(train_idx)+list(valid_idx)]
X_test = X.iloc[test_idx]
y_train = y.iloc[list(train_idx)+list(valid_idx)]
y_test = y.iloc[test_idx]
from xgboost import XGBClassifier

bst = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1)
bst.fit(X_train, y_train)
y_pred = bst.predict(X_test)
# Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(y_test, y_pred) * 100, "%")

Accuracy: 71.50587412299653 %


In [8]:
#Both
k = 80
feature = ["I_0", "O_0"]
for i in range(1, k - 1, 2):
    feature.append("I_{}".format(int((i + 1) / 2)))
    feature.append("O_{}".format(int((i + 1) / 2)))
for i in range(40):
    feature.append("C_{}".format(i))

X = data[feature]  # Features
y = data['Class']  # Labels
X_train = X.iloc[list(train_idx)+list(valid_idx)]
X_test = X.iloc[test_idx]
y_train = y.iloc[list(train_idx)+list(valid_idx)]
y_test = y.iloc[test_idx]
from xgboost import XGBClassifier

bst = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1)
bst.fit(X_train, y_train)
y_pred = bst.predict(X_test)
# Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(y_test, y_pred) * 100, "%")

Accuracy: 71.50587412299653 %
